export class Search{
    login:any;
    id:any;
    node_id:any;
    avatar_url:any;
    gravatar_id:any;
    url:any;
    html_url:any;
    followers_url:any;
    following_url:any;
    gists_url:any;
    starred_url:any;
    subscriptions_url:any;
    organizations_url:any;
    repos_url:any;
    events_url:any;
    received_events_url:any;
    type:any;
    site_admin:any;
    score:any;
}